### ISSUE TITLE
TypeError: evaluate() got an unexpected keyword argument 'return_outputs'

### ISSUE THREAD

**Issue by Mewscot** [Megvii-BaseDetection/YOLOX#1432]
![image](https://user-images.githubusercontent.com/109128662/178423349-faced12c-f72f-4ccf-8b6f-faa858a502c2.png)
I checked same issue happened, and i pull the newest version of code (which is today's code), and also i checked some solution and delete "return_outputs" under yolo_base.py def eval. But all of them doesn't work, please help me to check what happened here.

**Comment by FateScript** [comment]
Are you using the latest commit? This bug is fixed in #1416

**Comment by Mewscot** [comment]
> 

Yes, I pulled latest commit this morning

**Comment by Mewscot** [comment]
Hi, is there any possible update for this problem? I pulled latest commit and still face this problem.

**Comment by Mewscot** [comment]
Hi, when this bug can be fixed?

**Comment by qhtht** [comment]
> Hi, when this bug can be fixed?

I have the same promblem like yours, I have checked my code, it's the same as the newest, bu it still has the error. Have you solve it?
