### ISSUE TITLE
训练自己的数据集，到第三轮卡住不动，也没有报错

### ISSUE THREAD

**Issue by sunfei007** [Megvii-BaseDetection/YOLOX#341]
![image](https://user-images.githubusercontent.com/80185344/128030835-0ccae0f0-ed60-4d0f-ab47-3494d5f2960e.png)

**Comment by HIT-ShuWei** [comment]
you can try pulling the latest update, I fixed this problem by this way.

**Comment by ymw123** [comment]
I am using the latest version, and this problem still exists. I got stuck in the first epoch.

**Comment by ymw123** [comment]
> you can try pulling the latest update, I fixed this problem by this way.

I am using the latest version, and this problem still exists. I got stuck in the first epoch.

**Comment by anonymoussss** [comment]
I am using the latest version, and this problem still exists. I got stuck in the 291 epoch.

**Comment by xuezu29** [comment]
I am using the latest version,  I got stuck in the first epoch. Previous versions will not.

**Comment by sunfei007** [comment]
有人解决了这个问题吗

**Comment by ujsyehao** [comment]
有人定位到这个问题了吗

**Comment by Mobu59** [comment]
@sunfei007 你好 请问你解决或者定位到问题的原因了吗
