### ISSUE TITLE
Nano model training

### ISSUE THREAD

**Issue by abushattal1** [Megvii-BaseDetection/YOLOX#902]
hi there,
I am trying to train a "nano" model on custom dataset by using google Colab but I can't generate the train command because of "Exp" error.
note: I have checked the nano.py file and it is already updated
**here is the message:**
Traceback (most recent call last):
  File "/content/YOLOX/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nano'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 115, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/content/YOLOX/yolox/exp/build.py", line 51, in get_exp
    return get_exp_by_file(exp_file)
  File "/content/YOLOX/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: nano.py doesn't contains class named 'Exp'

**Comment by FateScript** [comment]
Did you use the latest commit, such a error is fixed a few week ago.

**Comment by abushattal1** [comment]
I just cloned the project but still get the same error .... pelase can you mention the latest commit for this error

**Comment by FateScript** [comment]
Did you modify any code in  nano?

**Comment by abushattal1** [comment]
Thank you for your reply and I appreciate your willingness to help. I checked the below code in nano.py file but it doesn't work

backbone = YOLOPAFPN(
                self.depth, self.width, in_channels=in_channels,
                act=self.act, depthwise=True,
            )
            head = YOLOXHead(
                self.num_classes, self.width, in_channels=in_channels,
                act=self.act, depthwise=True
            )

**Comment by FateScript** [comment]
So you are using nano with the latest commit and didn't modify anything, right?

**Comment by abushattal1** [comment]
> So you are using nano with the latest commit and didn't modify anything, right?

that's right

**Comment by JiaPai12138** [comment]
try this:
self.mosaic_prob = 1.0 instead of 0.5

**Comment by abushattal1** [comment]
> try this: self.mosaic_prob = 1.0 instead of 0.5

Thank you for your response... but still not working
